// Generated by https://quicktype.io

export interface RegisterResponse {
  kind:         string;
  idToken:      string;
  email:        string;
  refreshToken: string;
  expiresIn:    string;
  localId:      string;
}
